using BuildingBlocks.Application;
using BuildingBlocks.Application.Abstractions.Messaging;
using Microsoft.EntityFrameworkCore;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace BuildingBlocks.Infrastructure.Persistence
{
    public sealed class UnitOfWork : IUnitOfWork
    {
        private readonly DbContext _dbContext;
        private readonly IDomainEventDispatcher _domainEventDispatcher;

        public UnitOfWork(
            DbContext dbContext,
            IDomainEventDispatcher domainEventDispatcher)
        {
            _dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
            _domainEventDispatcher = domainEventDispatcher ?? throw new ArgumentNullException(nameof(domainEventDispatcher));
        }

        public async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
        {
            // Step 1: Save initial aggregate changes
            var result = await _dbContext.SaveChangesAsync(cancellationToken);

            // Step 2: Dispatch domain events (and execute handlers recursively if needed)
            await _domainEventDispatcher.DispatchAsync(cancellationToken);

            // Step 3: Save any secondary changes generated by event handlers (e.g. Audit Logs)
            if (_dbContext.ChangeTracker.HasChanges())
            {
                result += await _dbContext.SaveChangesAsync(cancellationToken);
            }

            return result;
        }
    }
}
